const BOOKINGS_PERMS = {
  CREATE_BOOKINGS: {
    PERMITTED_ROLES: ["STAFF", "MANAGER"],
    PERMITTED_POLICES: ["CREATE_BOOKINGS"],
  },
  READ_BOOKINGS: {
    PERMITTED_ROLES: ["STAFF", "MANAGER"],
    PERMITTED_POLICES: ["READ_BOOKINGS"],
  },
  DELETE_BOOKINGS: {
    PERMITTED_ROLES: ["MANAGER"],
    PERMITTED_POLICES: [ ],
  },
};
module.exports=BOOKINGS_PERMS
