const BOOKINGS_PERMS = {
  CREATE_BOOKINGS: {
    PERMITTED_ROLES: ["STAFF", "MANAGER"],
  },
  READ_BOOKINGS: {
    PERMITTED_ROLES: ["STAFF", "MANAGER"],
  },
  DELETE_BOOKINGS: {
    PERMITTED_ROLES: ["MANAGER"],
  },
};
module.exports=BOOKINGS_PERMS
